#!/usr/bin/env python3
"""Build the Calipic icon v1 refinement candidates from one parametric construction.

Usage (from the repo root):  scripts/brand/build-icon-v1.py

Writes
  docs/brand/assets/calipic-icon-v1-master.svg   flat master, full detail (>= 60 px)
  docs/brand/assets/calipic-icon-v1-small.svg    flat small-size master (< 60 px): no strand, wider gaps, heavier stroke
  docs/brand/prototypes/icon-v1/                 finished (depth/shadow/texture) variants, PNG renders, comparison sheets

The flat masters keep the v0 colour tokens (#111111 mark, #FFFFFF field and strand, #D9D9D9 keyline) so the
round-1 evidence scripts (render-color-matrix.sh, render-icon-sizes.sh, render-a11y.sh) re-run on them unchanged.

Geometry is exact by construction: every frame segment is generated from the same numbers and mirrored around
y = 512, so symmetry, stroke, radii and caps cannot drift. Stdlib only; PNGs are rendered with inkscape.
"""
import os
import shutil
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ASSETS = os.path.join(ROOT, "docs/brand/assets")
OUT = os.path.join(ROOT, "docs/brand/prototypes/icon-v1")

C = 512  # canvas centre; canvas is 1024


class Spec:
    """One construction. All values are in 1024-canvas units."""

    def __init__(self, stroke, net_gap, strand, left=180, right=844, top=180, radius=130, shift_x=0):
        self.stroke = stroke      # uniform frame stroke
        self.net_gap = net_gap    # visible gap between round caps (top, bottom, left)
        self.strand = strand      # negative-space strand width; 0 = omitted
        self.left, self.right, self.top, self.radius = left, right, top, radius
        self.shift_x = shift_x    # optical correction for the open right side


FULL = Spec(stroke=64, net_gap=30, strand=22)
SMALL = Spec(stroke=76, net_gap=44, strand=0)


def frame_paths(s):
    """Four segments. Small gaps top/bottom/left; the right corners simply end, leaving the wide C opening."""
    L, R, T, r = s.left + s.shift_x, s.right + s.shift_x, s.top, s.radius
    B = 2 * C - T
    cx = (L + R) / 2
    g = (s.net_gap + s.stroke) / 2  # half the centre-line gap (caps are round, radius stroke/2)
    top_left = f"M {cx - g:g} {T} H {L + r} A {r} {r} 0 0 0 {L} {T + r} V {C - g:g}"
    bot_left = f"M {cx - g:g} {B} H {L + r} A {r} {r} 0 0 1 {L} {B - r} V {C + g:g}"
    top_right = f"M {cx + g:g} {T} H {R - r} A {r} {r} 0 0 1 {R} {T + r}"
    bot_right = f"M {cx + g:g} {B} H {R - r} A {r} {r} 0 0 0 {R} {B - r}"
    return [top_left, bot_left, top_right, bot_right]


def bust_paths(s):
    """Front-facing bust: bun, head, neck and shoulders as one silhouette, plus the loose lock."""
    x = C + s.shift_x
    bun = f'<ellipse cx="{x + 14}" cy="300" rx="50" ry="42"/>'
    # Head: slightly egg-shaped (fuller crown, narrower jaw) rather than a plain ellipse.
    head = (f'<path d="M {x} 322 C {x + 76} 322 {x + 122} 382 {x + 122} 456 '
            f'C {x + 122} 536 {x + 70} 598 {x} 598 C {x - 70} 598 {x - 122} 536 {x - 122} 456 '
            f'C {x - 122} 382 {x - 76} 322 {x} 322 Z"/>')
    # Neck flows into the shoulders in one continuous curve; the base is flat like a cropped print.
    body = (f'<path d="M {x - 48} 570 C {x - 48} 630 {x - 58} 652 {x - 96} 664 '
            f'C {x - 160} 682 {x - 204} 712 {x - 218} 760 H {x + 218} '
            f'C {x + 204} 712 {x + 160} 682 {x + 96} 664 C {x + 58} 652 {x + 48} 630 {x + 48} 570 Z"/>')
    parts = [bun, head, body]
    if s.strand:
        # Loose lock hanging past the jaw on the left; the strand cut separates it from the face.
        parts.append(f'<path d="M {x - 116} 440 C {x - 146} 500 {x - 146} 580 {x - 118} 640 '
                     f'C {x - 112} 652 {x - 104} 660 {x - 96} 664 C {x - 100} 620 {x - 100} 560 {x - 84} 510 Z"/>')
    return parts


def strand_path(s):
    x = C + s.shift_x
    return (f"M {x + 72} 336 C {x + 70} 404 {x + 30} 436 {x - 18} 466 "
            f"C {x - 66} 496 {x - 90} 536 {x - 86} 586 C {x - 84} 612 {x - 88} 636 {x - 97} 656")


def flat_svg(s, title):
    frame = "\n    ".join(f'<path d="{d}"/>' for d in frame_paths(s))
    bust = "\n    ".join(bust_paths(s))
    strand = (f'\n  <path d="{strand_path(s)}" fill="none" stroke="#FFFFFF" stroke-width="{s.strand}" '
              f'stroke-linecap="round"/>') if s.strand else ""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" role="img" aria-labelledby="title desc">
  <title id="title">{title}</title>
  <desc id="desc">A portrait bust inside a rounded crop frame with small gaps at top, bottom and left and a wide opening on the right, so the frame reads as a capital C.</desc>
  <!-- Generated by scripts/brand/build-icon-v1.py. Do not hand-edit; change the Spec and rebuild. -->
  <rect x="28" y="28" width="968" height="968" rx="216" fill="#FFFFFF" stroke="#D9D9D9" stroke-width="4"/>
  <g fill="none" stroke="#111111" stroke-width="{s.stroke}" stroke-linecap="round" stroke-linejoin="round">
    {frame}
  </g>
  <g fill="#111111">
    {bust}
  </g>{strand}
</svg>
'''


# Finalists from docs/brand/prototypes/05-color-recommendation.md. Test values (BD-037), not decisions.
FINISHES = {
    "B-teal": {"top": "#15899A", "bottom": "#0A5863", "strand": "#0E6F7C"},
    "A-blue": {"top": "#2B50C8", "bottom": "#162F86", "strand": "#1F3FA8"},
}


def finished_svg(s, name, f):
    """Full-bleed square (the system applies the icon mask). Depth comes from three restrained layers:
    a lit field with paper grain, a soft contact shadow, and a faintly modelled white mark."""
    frame = "\n      ".join(f'<path d="{d}"/>' for d in frame_paths(s))
    bust = "\n      ".join(bust_paths(s))
    cut = (f'<path d="{strand_path(s)}" fill="none" stroke="#000000" stroke-width="{s.strand}" '
           f'stroke-linecap="round"/>') if s.strand else ""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <title>Calipic icon v1 - finished study {name}</title>
  <!-- Generated by scripts/brand/build-icon-v1.py. Study, not a production asset. -->
  <defs>
    <linearGradient id="field" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{f["top"]}"/><stop offset="1" stop-color="{f["bottom"]}"/>
    </linearGradient>
    <radialGradient id="light" cx="0.3" cy="0.12" r="0.9">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.22"/><stop offset="0.6" stop-color="#FFFFFF" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="mark" gradientUnits="userSpaceOnUse" x1="0" y1="150" x2="0" y2="880">
      <stop offset="0" stop-color="#FFFFFF"/><stop offset="1" stop-color="#E4EEF1"/>
    </linearGradient>
    <filter id="grain" x="0" y="0" width="1" height="1" color-interpolation-filters="sRGB">
      <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="2" seed="7" result="n"/>
      <feColorMatrix in="n" type="matrix" values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0.33 0.33 0.33 0 -0.28"/>
    </filter>
    <filter id="shadow" x="-0.2" y="-0.2" width="1.4" height="1.4" color-interpolation-filters="sRGB">
      <feGaussianBlur in="SourceAlpha" stdDeviation="14"/>
      <feOffset dy="14"/>
      <feComponentTransfer><feFuncA type="linear" slope="0.30"/></feComponentTransfer>
    </filter>
    <mask id="cut" maskUnits="userSpaceOnUse" x="0" y="0" width="1024" height="1024">
      <rect width="1024" height="1024" fill="#FFFFFF"/>{cut}
    </mask>
    <g id="glyph" mask="url(#cut)">
      <g fill="none" stroke-width="{s.stroke}" stroke-linecap="round" stroke-linejoin="round">
      {frame}
      </g>
      <g stroke="none">
      {bust}
      </g>
    </g>
  </defs>
  <rect width="1024" height="1024" fill="url(#field)"/>
  <rect width="1024" height="1024" fill="url(#light)"/>
  <rect width="1024" height="1024" filter="url(#grain)" opacity="0.10"/>
  <use href="#glyph" fill="#000000" stroke="#000000" filter="url(#shadow)"/>
  <use href="#glyph" fill="url(#mark)" stroke="url(#mark)"/>
</svg>
'''


def inkscape(svg, png, width):
    subprocess.run(["inkscape", svg, "--export-type=png", "-w", str(width), "-o", png],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def sheet(path, rows, sizes, title, note):
    """rows: [(label, {size: png_filename})]. Icons are shown at true pixel size, masked."""
    pad, label_w, gap = 48, 250, 40
    width = pad * 2 + label_w + sum(sizes) + gap * len(sizes)
    row_h = max(sizes) + 70
    height = 150 + row_h * len(rows) + 40
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
           f'width="{width}" height="{height}" viewBox="0 0 {width} {height}" font-family="Helvetica, Arial, sans-serif">',
           f'<rect width="{width}" height="{height}" fill="#F2F2F7"/>',
           f'<text x="{pad}" y="62" font-size="34" font-weight="700" fill="#111">{title}</text>',
           f'<text x="{pad}" y="100" font-size="20" fill="#555">{note}</text>']
    y = 150
    n = 0
    for label, files in rows:
        out.append(f'<text x="{pad}" y="{y + 40}" font-size="24" font-weight="700" fill="#111">{label}</text>')
        x = pad + label_w
        for px in sizes:
            n += 1
            rx = 0.2237 * px
            out.append(f'<clipPath id="c{n}"><rect x="{x}" y="{y}" width="{px}" height="{px}" rx="{rx:.2f}"/></clipPath>')
            out.append(f'<image xlink:href="{files[px]}" x="{x}" y="{y}" width="{px}" height="{px}" '
                       f'clip-path="url(#c{n})" style="image-rendering:pixelated"/>')
            out.append(f'<rect x="{x}" y="{y}" width="{px}" height="{px}" rx="{rx:.2f}" fill="none" stroke="#00000018"/>')
            out.append(f'<text x="{x}" y="{y + px + 26}" font-size="16" fill="#666">{px} px</text>')
            x += px + gap
        y += row_h
    out.append("</svg>")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    inkscape(path, path[:-4] + ".png", width)  # natural width, so every icon keeps its true pixels
    os.remove(path)


def main():
    if not shutil.which("inkscape"):
        sys.exit("inkscape is required")
    os.makedirs(OUT, exist_ok=True)
    master = os.path.join(ASSETS, "calipic-icon-v1-master.svg")
    small = os.path.join(ASSETS, "calipic-icon-v1-small.svg")
    with open(master, "w") as fh:
        fh.write(flat_svg(FULL, "Calipic icon v1 master (refinement candidate)"))
    with open(small, "w") as fh:
        fh.write(flat_svg(SMALL, "Calipic icon v1 small-size master (refinement candidate)"))

    sizes = [512, 180, 120, 87, 60, 40, 29]
    rows = []
    v0 = os.path.join(ASSETS, "calipic-icon-draft-v0.svg")
    for label, svg, stem in [("v0 draft (flat)", v0, "v0-flat"), ("v1 master (flat)", master, "v1-flat"),
                             ("v1 small master", small, "v1-small-flat")]:
        files = {}
        for px in sizes:
            files[px] = f"{stem}-{px}.png"
            inkscape(svg, os.path.join(OUT, files[px]), px)
        rows.append((label, files))
    sheet(os.path.join(OUT, "sheet-geometry.svg"), rows, sizes,
          "Calipic icon - v0 draft vs v1 geometry (flat)", "True pixel sizes. v1 small master is intended for sizes below 60 px.")

    rows = []
    for name, f in FINISHES.items():
        files = {}
        full_svg = os.path.join(OUT, f"v1-finished-{name}.svg")
        small_svg = os.path.join(OUT, f"v1-finished-{name}-small.svg")
        with open(full_svg, "w") as fh:
            fh.write(finished_svg(FULL, name, f))
        with open(small_svg, "w") as fh:
            fh.write(finished_svg(SMALL, name + " small", f))
        inkscape(full_svg, os.path.join(OUT, f"v1-finished-{name}-1024.png"), 1024)
        for px in sizes:
            files[px] = f"v1-finished-{name}-{px}.png"
            inkscape(full_svg if px >= 60 else small_svg, os.path.join(OUT, files[px]), px)
        rows.append((f"v1 finished {name}", files))
    sheet(os.path.join(OUT, "sheet-finished.svg"), rows, sizes,
          "Calipic icon v1 - finished studies (depth, shadow, grain)",
          "Full master at 60 px and above, small master below. Test colours (BD-037), not decisions.")
    print("built", master, small, OUT)


if __name__ == "__main__":
    main()
